# Generated by Django 4.2.3 on 2024-07-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Website_v1', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_paragraph1',
            field=models.TextField(default='More Content Will Be Added Soon'),
        ),
        migrations.AddField(
            model_name='project',
            name='detail_paragraph2',
            field=models.TextField(default='More Content Will Be Added Soon'),
        ),
        migrations.AddField(
            model_name='project',
            name='detail_paragraph3',
            field=models.TextField(default='More Content Will Be Added Soon'),
        ),
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.ImageField(default='More Content Will Be Added Soon', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image5',
            field=models.ImageField(default='More Content Will Be Added Soon', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image6',
            field=models.ImageField(default='More Content Will Be Added Soon', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(default='More Content Will Be Added Soon'),
        ),
    ]
