# Generated by Django 4.2.3 on 2024-07-17 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('The_Website_v1', '0003_project_detail_paragraph1_project_detail_paragraph2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='detail_paragraph1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='detail_paragraph2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='detail_paragraph3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image6',
        ),
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(default='More Content Will Be Added Soon', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(default='More Content Will Be Added Soon', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(default='More Content Will Be Added Soon', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField()),
                ('detail_paragraph1', models.TextField(default='More Content Will Be Added Soon')),
                ('detail_paragraph2', models.TextField(default='More Content Will Be Added Soon')),
                ('detail_paragraph3', models.TextField(default='More Content Will Be Added Soon')),
                ('image4', models.ImageField(default='More Content Will Be Added Soon', upload_to='images/')),
                ('image5', models.ImageField(default='More Content Will Be Added Soon', upload_to='images/')),
                ('image6', models.ImageField(default='More Content Will Be Added Soon', upload_to='images/')),
                ('live_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='The_Website_v1.project')),
            ],
        ),
    ]
