# Generated by Django 4.2.3 on 2024-07-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Website_v1', '0005_remove_project_overview_alter_projectdetail_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image01',
            field=models.ImageField(default='More Content Will Be Added Soon', upload_to='images/'),
        ),
    ]
